### PR TITLE
Use Camunda Parent POM for Deps Generation + Dynamic Config of Dep version based on Camunda Version

### PR DESCRIPTION
**Pull request by menski**
Import Camunda parent pom for the logging dependency versions and the spin root pom for the jackson dependency versions. Also remove Camunda version from artifact id but add it to the final artifact name, i.e. `camunda-json-logging-tomcat-7.9.0-jar-with-dependencies.jar`. To upgrade or build for other camunda version only the properties `version.camunda` and `version.camunda.spin` have to be updated or overridden.

### CODE REVIEW

**Comment by StephenOTT** [comment]
@menski this looks good.  I have added a additional change to your config that removes the jar-with-dependencies naming in the jar.  Thoughts?

**Comment by StephenOTT** [comment]
@menski also if we are going to add the camunda version into the name, then we should consider adding the Camunda version as a ENV of the container, so we can use it to locate the specific version of the jar in the setenv.sh file.  Otherwise we need to keep multiple configs of the setenv.sh file i believe (unless setenv supports wildcards)...

**Comment by menski** [comment]
Sorry I didn't checked the docker image with my changes. :see_no_evil: 

I assume Java classpaths supports wildcards, other then that there is already an environment variable in the image with the camunda version.

https://github.com/camunda/docker-camunda-bpm-platform/blob/master/Dockerfile#L3

I will have a look later regarding the docker setup.

**Comment by StephenOTT** [comment]
That is a Argment.. does it come throuhg on the image? 

)

**Comment by StephenOTT** [comment]
@menski i believe the issue for wildcard classpath is that it only supports wildcard at the base such as `some/path/folder123/*`  Where we need `some/path/folder123/myjar-*`.  I just tested this and it does not work.

And the Camunda version ENV is not created in your base Camunda image as per the use of ARG vs ENV.

doing a docker inspect on the camunda image you can see:

```
"Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin",
                "LANG=C.UTF-8",
                "JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre",
                "JAVA_VERSION=8u151",
                "JAVA_ALPINE_VERSION=8.151.12-r0",
                "DB_DRIVER=org.h2.Driver",
                "DB_URL=jdbc:h2:./camunda-h2-dbs/process-engine;MVCC=TRUE;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE",
                "DB_USERNAME=sa",
                "DB_PASSWORD=sa",
                "SKIP_DB_CONFIG=",
                "WAIT_FOR=",
                "WAIT_FOR_TIMEOUT=30",
                "TZ=UTC",
                "DEBUG=false"
            ],
```

**Comment by StephenOTT** [comment]
@menski as a test i confirmed we can use the version number with the setenv.  If you can expose the VERSION env as a ENV and not sure a ARG within the upstream image then we can update the setenv.sh to:

`CLASSPATH=$CATALINA_HOME/lib/camunda-json-logging-tomcat-${VERSION}.jar:$CATALINA_HOME/conf/logback/`

and everything works as expected

**Comment by menski** [comment]
Sorry I mixed that up with the ARG as it is also set in the builder image, so not sure if I get it into the final image.

Alternative we could use a wildcard in the COPY statement of your Dockerfile to have the jar always have the same name inside your image and easily be referenced by a static name in the setenv.sh, what to you think about this solution?

**Comment by menski** [comment]
The Camunda images will now contain a environment variable `CAMUNDA_VERSION` which is the version the image was build for (see https://github.com/camunda/docker-camunda-bpm-platform/commit/61fc22bf42a2603583ef15d9937627438a8977c8).

**Comment by StephenOTT** [comment]
@menski okay image has been updated on dockerhub(digitalstate/camunda-bpm-platform), and the proper configs are now in place to use the new ENV `CAMUNDA_VERSION` in the setenv.sh file

**Pull request merged**
